baseURL = "https://ciatastrophe.netlify.com/"
languageCode = "en-us"
title = "Ciatastrophe"
theme = "ghostwriter"
disqusShortname = "https-ciatastrophe-netlify-com"


[Params]
    intro = true
    headline = "Anastasia 💻"
    description = "| My HolidayCheck Apprenticeship Blog - Stay Tuned!"
    github = "https://github.com/ciaskious"
    linkedin = "https://linkedin.com/in/anastasia-kaloudi93/"
    twitter = "https://twitter.com/anaskaloudi"

[Author]
    name = "Anastasia"


[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
